version: 2 

models:
  - name: clients
    description: This table list the clients informations 
    columns:
      - name: email
        description: this column contain email of the clients 
        tests:
          - unique
          - dbt_expectations.expect_column_values_to_be_of_type: 
              arguments: 
                column_type: string
          - dbt_expectations.expect_column_values_to_match_regex:
              arguments:
                regex: '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
              config:
                where: "email IS NOT NULL AND TRIM(email) != ''"
                severity: warn 
      - name: created_at
        description: give the first date of the client registration 
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type: 
              arguments: 
                column_type: timestamp
      - name: client_id 
        description: client identifier 
        tests:
          - not_null
          - unique 
          
          
          
          
          